package com.mini.fintech.wallet_app.common.util;

import java.util.Set;

public enum ErrorCode {
	RESOURCE_NOT_FOUND, VALIDATION_ERROR, INTERNAL_ERROR, WALLET_ALREADY_EXISTS, WALLET_INACTIVE, INSUFFICIENT_FUNDS,
	INVALID_CURRENCY, INVALID_TRANSFER, REQUEST_ALREADY_IN_PROGRESS, CONCURRENT_MODIFICATION, IDEMPOTENCY_KEY_REUSED,
	IDEMPOTENCY_KEY_REQUIRED, TRANSFER_NOT_REVERSIBLE, REVERSAL_INSUFFICIENT_FUNDS, TRANSFER_ALREADY_REVERSED;

	public static final Set<String> CONFLICT_CODES = Set.of(CONCURRENT_MODIFICATION.name(),
			WALLET_ALREADY_EXISTS.name(), IDEMPOTENCY_KEY_REUSED.name(), REQUEST_ALREADY_IN_PROGRESS.name(),
			TRANSFER_NOT_REVERSIBLE.name());

}
